name: Deploy to AWS with Terraform

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-north-1  # Replace with your AWS region
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Debug AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
      
      - name: Install AWS CLI
        run: sudo apt-get install -y awscli
      
      - name: Configure AWS CLI
        run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set default.region $AWS_DEFAULT_REGION
      
      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_linux_amd64.zip
          unzip terraform_0.15.0_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
      
      - name: Initialize Terraform
        run: terraform init
      
      - name: Validate Terraform Configuration
        run: terraform validate
      
      - name: Plan Terraform Changes
        run: terraform plan -out=tfplan
      
      - name: Apply Terraform Changes
        run: terraform apply -auto-approve tfplan
